### ISSUE TITLE
Misleading error messages and panics when compiling queries referencing non-existing relation

### ISSUE THREAD

**Issue by balogal** [kyleconroy/sqlc#1051]
When processing queries that reference a non-existing relation `sqlc compile` and `sqlc generate` output misleading error messages or even panic for some queries. On a first glance, it appears that the bug only shows when placeholders are used in the query. I could reproduce the following playground examples locally using:

- sqlc version `v1.8.0`
- engine: `postgresql`
- minimal sqlc config file, defining solely the properties `name`, `path`, `queries` and `schema` and `engine`

Examples:

(1) - [playground link](https://play.sqlc.dev/p/e8ce9dc87e16b2c9e434024e196b165c0673064a62c52691ce42f1c3786ac0e8)

This example works as I would expect. From the error message, I can easily determine what is wrong with my query.

```
-- name: Get :many
SELECT * FROM nonexisting_relation WHERE name = 'foo';

output:
query.sql:1:1: relation "nonexisting_relation" does not exist
```

(2) - [playground link](https://play.sqlc.dev/p/45b085c22e5985cd54add894525c05235bb430ad9cadf419b15e60a8494ed7c3)

Would expect a 'relation does not exist' error as above. 'Column does not exist' is misleading.

```
-- name: Get :many
SELECT * FROM nonexisting_relation WHERE name = $1;

output:
query.sql:2:42: column "name" does not exist
```

(3) - [playground link](https://play.sqlc.dev/p/6a47b21213c4fda838a0d4473be5f1b6ed7473c331cccf2ecd2eca9a66ef029c)

Would expect to get a 'relation does not exist error' instead of panic.

```
-- name: Update :exec
UPDATE nonexisting_relation SET name = $1;

output:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xdafc51]

goroutine 1 [running]:
github.com/kyleconroy/sqlc/internal/compiler.resolveCatalogRefs(0xc0000c5500, 0xc000010808, 0x1, 0x1, 0xc000530900, 0x1, 0x1, 0xc000530750, 0x0, 0x8, ...)
	/go/pkg/mod/github.com/kyleconroy/sqlc@v1.8.0/internal/compiler/resolve.go:301 +0x1711
github.com/kyleconroy/sqlc/internal/compiler.(*Compiler).parseQuery(0xc00046c800, 0x1304e80, 0xc000591580, 0xc0001ea180, 0x40, 0x0, 0x0, 0x0, 0xfd4aa0)
	/go/pkg/mod/github.com/kyleconroy/sqlc@v1.8.0/internal/compiler/parse.go:90 +0x577
github.com/kyleconroy/sqlc/internal/compiler.(*Compiler).parseQueries(0xc00046c800, 0x1000000, 0xc0000c5500, 0xc00058f810, 0x1)
	/go/pkg/mod/github.com/kyleconroy/sqlc@v1.8.0/internal/compiler/compile.go:109 +0x58c
github.com/kyleconroy/sqlc/internal/compiler.(*Compiler).ParseQueries(...)
	/go/pkg/mod/github.com/kyleconroy/sqlc@v1.8.0/internal/compiler/engine.go:49
github.com/kyleconroy/sqlc/internal/cmd.parse(0xc0000d3500, 0xc0001168fc, 0x2, 0xc000182180, 0x57, 0xc000116906, 0xa, 0xc00058f810, 0x1, 0x1, ...)
	/go/pkg/mod/github.com/kyleconroy/sqlc@v1.8.0/internal/cmd/generate.go:223 +0x135
github.com/kyleconroy/sqlc/internal/cmd.Generate(0x1a1e700, 0xc000182180, 0x57, 0x0, 0x0, 0x13097a0, 0xc0001a0010, 0x0, 0x10d0fe7, 0x32)
	/go/pkg/mod/github.com/kyleconroy/sqlc@v1.8.0/internal/cmd/generate.go:167 +0xcc9
github.com/kyleconroy/sqlc/internal/cmd.glob..func3(0x1a1e7a0, 0x1f6f578, 0x0, 0x0)
	/go/pkg/mod/github.com/kyleconroy/sqlc@v1.8.0/internal/cmd/cmd.go:120 +0x170
github.com/spf13/cobra.(*Command).execute(0x1a1e7a0, 0x1f6f578, 0x0, 0x0, 0x1a1e7a0, 0x1f6f578)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000c2a00, 0xc0001cdf10, 0x1, 0x1)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/kyleconroy/sqlc/internal/cmd.Do(0xc0001a4010, 0x1, 0x1, 0x1309760, 0xc0001a0000, 0x13097a0, 0xc0001a0008, 0x13097a0, 0xc0001a0010, 0xc000182058)
	/go/pkg/mod/github.com/kyleconroy/sqlc@v1.8.0/internal/cmd/cmd.go:34 +0x317
main.main()
	/go/pkg/mod/github.com/kyleconroy/sqlc@v1.8.0/cmd/sqlc/main.go:10 +0xb7
```

(4) - [playground link](https://play.sqlc.dev/p/adf7880260ce01812535f6d7539369288179a5c0bbce9be8ae6a4048895dfc42)

Would expect to get a 'relation does not exist error' instead of panic.

```
-- name: Create :exec
INSERT INTO nonexisting_relation (id) VALUES ($1);

output:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xdafc51]

goroutine 1 [running]:
github.com/kyleconroy/sqlc/internal/compiler.resolveCatalogRefs(0xc0004e53b0, 0xc000467cd8, 0x1, 0x1, 0xc000720120, 0x1, 0x1, 0xc000720090, 0x0, 0x8, ...)
	/go/pkg/mod/github.com/kyleconroy/sqlc@v1.8.0/internal/compiler/resolve.go:301 +0x1711
github.com/kyleconroy/sqlc/internal/compiler.(*Compiler).parseQuery(0xc0003ec800, 0x1304e80, 0xc000021f20, 0xc0000480f0, 0x48, 0x0, 0x0, 0x0, 0xfd4aa0)
	/go/pkg/mod/github.com/kyleconroy/sqlc@v1.8.0/internal/compiler/parse.go:90 +0x577
github.com/kyleconroy/sqlc/internal/compiler.(*Compiler).parseQueries(0xc0003ec800, 0x1000000, 0xc0004e53b0, 0xc000121ae0, 0x1)
	/go/pkg/mod/github.com/kyleconroy/sqlc@v1.8.0/internal/compiler/compile.go:109 +0x58c
github.com/kyleconroy/sqlc/internal/compiler.(*Compiler).ParseQueries(...)
	/go/pkg/mod/github.com/kyleconroy/sqlc@v1.8.0/internal/compiler/engine.go:49
github.com/kyleconroy/sqlc/internal/cmd.parse(0xc0004f5500, 0xc00050131c, 0x2, 0xc00009c180, 0x57, 0xc000501326, 0xa, 0xc000121ae0, 0x1, 0x1, ...)
	/go/pkg/mod/github.com/kyleconroy/sqlc@v1.8.0/internal/cmd/generate.go:223 +0x135
github.com/kyleconroy/sqlc/internal/cmd.Generate(0x1a1e700, 0xc00009c180, 0x57, 0x0, 0x0, 0x13097a0, 0xc000010020, 0x0, 0x10d0fe7, 0x32)
	/go/pkg/mod/github.com/kyleconroy/sqlc@v1.8.0/internal/cmd/generate.go:167 +0xcc9
github.com/kyleconroy/sqlc/internal/cmd.glob..func3(0x1a1e7a0, 0x1f6f578, 0x0, 0x0)
	/go/pkg/mod/github.com/kyleconroy/sqlc@v1.8.0/internal/cmd/cmd.go:120 +0x170
github.com/spf13/cobra.(*Command).execute(0x1a1e7a0, 0x1f6f578, 0x0, 0x0, 0x1a1e7a0, 0x1f6f578)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004e6280, 0xc0000d1f10, 0x1, 0x1)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/kyleconroy/sqlc/internal/cmd.Do(0xc00000e070, 0x1, 0x1, 0x1309760, 0xc000010010, 0x13097a0, 0xc000010018, 0x13097a0, 0xc000010020, 0xc00009c058)
	/go/pkg/mod/github.com/kyleconroy/sqlc@v1.8.0/internal/cmd/cmd.go:34 +0x317
main.main()
	/go/pkg/mod/github.com/kyleconroy/sqlc@v1.8.0/cmd/sqlc/main.go:10 +0xb7
```

Might be related to #1038

**Comment by kyleconroy** [comment]
@balogal Thanks for the fantastic error report, especially the included playground links. I agree that all of these examples should return the error `relation "nonexisting_relation" does not exist`. sqlc shouldn't panic often, and it's obvious that's currently not the case.

**Comment by gdexlab** [comment]
I just noticed this one today too, after changing a table name without updating my queries or sqlc.json config references.
