### ISSUE TITLE
Generate fails for DELETE with INNER JOIN

### ISSUE THREAD

**Issue by asterikx** [kyleconroy/sqlc#1083]
MySQL DELETE with INNER JOIN panics with `panic: expected range var`

Playground: https://play.sqlc.dev/p/5b48df99acc6cb56a4105f836166a35b42f840acf43709d8cc133040da77ce79

**Comment by MaksimSkorobogatov** [comment]
Hello!

I got the same panic too.

```
./tools/bin/sqlc -f internal/db/sqlc.yaml generate
panic: expected range var

goroutine 1 [running]:
github.com/kyleconroy/sqlc/internal/engine/dolphin.(*cc).convertDeleteStmt(0x203000, 0xc0003e19d0)
        /home/maksim/go/pkg/mod/github.com/kyleconroy/sqlc@v1.10.0/internal/engine/dolphin/convert.go:294 +0x13b
github.com/kyleconroy/sqlc/internal/engine/dolphin.(*cc).convert(0xc00042e100, {0x1238580, 0xc0003e19d0})
        /home/maksim/go/pkg/mod/github.com/kyleconroy/sqlc@v1.10.0/internal/engine/dolphin/convert.go:1291 +0x977
github.com/kyleconroy/sqlc/internal/engine/dolphin.(*Parser).Parse(0xc000118540, {0x1223fa0, 0xc0001c00e0})
        /home/maksim/go/pkg/mod/github.com/kyleconroy/sqlc@v1.10.0/internal/engine/dolphin/parse.go:64 +0x18c
github.com/kyleconroy/sqlc/internal/compiler.(*Compiler).parseQueries(0xc0001e4b40, {0x10, {0x4, 0x51}})
        /home/maksim/go/pkg/mod/github.com/kyleconroy/sqlc@v1.10.0/internal/compiler/compile.go:102 +0x395
github.com/kyleconroy/sqlc/internal/compiler.(*Compiler).ParseQueries(...)
        /home/maksim/go/pkg/mod/github.com/kyleconroy/sqlc@v1.10.0/internal/compiler/engine.go:49
github.com/kyleconroy/sqlc/internal/cmd.parse({_}, {_, _}, {_, _}, {{0xc00011dcb8, 0x5}, {0xc000510410, 0x1, 0x1}, ...}, ...)
        /home/maksim/go/pkg/mod/github.com/kyleconroy/sqlc@v1.10.0/internal/cmd/generate.go:223 +0x1d4
github.com/kyleconroy/sqlc/internal/cmd.Generate({0xc0}, {0xc0001ce0a0, 0x3a}, {0xc0001ce0db, 0x2}, {0x1223ec0, 0xc00019c010})
        /home/maksim/go/pkg/mod/github.com/kyleconroy/sqlc@v1.10.0/internal/cmd/generate.go:167 +0xb77
github.com/kyleconroy/sqlc/internal/cmd.glob..func3(0x19d3ca0, {0xf93859, 0x2, 0x2})
        /home/maksim/go/pkg/mod/github.com/kyleconroy/sqlc@v1.10.0/internal/cmd/cmd.go:120 +0xf7
github.com/spf13/cobra.(*Command).execute(0x19d3ca0, {0xc00061cdc0, 0x2, 0x2})
        /home/maksim/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000f6a00)
        /home/maksim/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/maksim/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/kyleconroy/sqlc/internal/cmd.Do({0xc0001a0010, 0x3, 0x3}, {0x1223e80, 0xc00019c000}, {0x1223ec0, 0xc00019c008}, {0x1223ec0, 0xc00019c010})
        /home/maksim/go/pkg/mod/github.com/kyleconroy/sqlc@v1.10.0/internal/cmd/cmd.go:34 +0x32e
main.main()
        /home/maksim/go/pkg/mod/github.com/kyleconroy/sqlc@v1.10.0/cmd/sqlc/main.go:10 +0x7a
make: *** [Makefile:72: generate-sqlc] Ошибка 2
```

SQL query:

```SQL
-- name: DeleteListWithObjects :execrows
DELETE l.*, o.*
FROM lists l
         LEFT JOIN objects o ON o.list_id = l.id
WHERE l.id = ?;
```

Version: `v1.10.0`

OS: `Linux`

Engine: `MySQL`

I can open a PR to fix.
