### ISSUE TITLE
jsonb_extract_path_text cause parser panic

### ISSUE THREAD

**Issue by elvizlai** [kyleconroy/sqlc#1952]
### Version

Other

### What happened?

Using version 1.16.0, it panic when `sqlc generate`, which works fine in 1.15.0

```
-- name: XXXX :exec
select coalesce(jsonb_extract_path_text('{}'::jsonb, @path1, @path2), '') as name;
```

### Relevant log output

```shell
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
github.com/kyleconroy/sqlc/internal/compiler.(*Compiler).resolveCatalogRefs(0xc0002e9ab0?, 0xc000b02a90, {0x0, 0x0, 0xc00080f3a5?}, {0xc000a34180, 0x2, 0x40?}, 0xc000b5a2d0)
	/Users/runner/work/release-sqlc/release-sqlc/internal/compiler/resolve.go:332 +0x2e17
github.com/kyleconroy/sqlc/internal/compiler.(*Compiler).parseQuery(0xc00037cc00, {0x101e622e0?, 0xc000ade480?}, {0xc00080e000, 0x13ef}, {{0x20?, 0x9b?, {0x0?, 0x8?}}})
	/Users/runner/work/release-sqlc/release-sqlc/internal/compiler/parse.go:91 +0x7cd
github.com/kyleconroy/sqlc/internal/compiler.(*Compiler).parseQueries(0xc00037cc00, {{0x80?, 0xbe?, {0x0?, 0x1?}}})
	/Users/runner/work/release-sqlc/release-sqlc/internal/compiler/compile.go:108 +0x4da
github.com/kyleconroy/sqlc/internal/compiler.(*Compiler).ParseQueries(...)
	/Users/runner/work/release-sqlc/release-sqlc/internal/compiler/engine.go:49
github.com/kyleconroy/sqlc/internal/cmd.parse({_, _}, {_, _}, {_, _}, {_, _}, {{0xc00020b350, 0xa}, ...}, ...)
	/Users/runner/work/release-sqlc/release-sqlc/internal/cmd/generate.go:277 +0x25b
github.com/kyleconroy/sqlc/internal/cmd.Generate({0x101e6c830, 0xc00004a0a8}, {0x0?, 0x0?}, {0xc000044044, 0x3a}, {0x0?, 0x0?}, {0x101e671c0, 0xc000014020})
	/Users/runner/work/release-sqlc/release-sqlc/internal/cmd/generate.go:219 +0x80d
github.com/kyleconroy/sqlc/internal/cmd.glob..func3(0x102ea32e0, {0x1018d5765?, 0x0?, 0x0?})
	/Users/runner/work/release-sqlc/release-sqlc/internal/cmd/cmd.go:147 +0x194
github.com/spf13/cobra.(*Command).execute(0x102ea32e0, {0x102f17708, 0x0, 0x0})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001a6c00)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:961
github.com/kyleconroy/sqlc/internal/cmd.Do({0xc000040050, 0x1, 0x1}, {0x101e67180?, 0xc000014010}, {0x101e671c0?, 0xc000014018}, {0x101e671c0?, 0xc000014020})
	/Users/runner/work/release-sqlc/release-sqlc/internal/cmd/cmd.go:50 +0x487
main.main()
	/Users/runner/work/release-sqlc/release-sqlc/cmd/sqlc/main.go:10 +0x78
```
```


### Database schema

_No response_

### SQL queries

```sql
select coalesce(jsonb_extract_path_text('{}'::jsonb, @path1, @path2), '') as name;
```

**Comment by elvizlai** [comment]
should fix sql with
```
select coalesce(jsonb_extract_path_text('{}'::jsonb, @path::text[]), '') as name;
```

**Comment by elvizlai** [comment]
It finally works with keyword `VARIADIC`

```
SELECT jsonb_extract_path_text('{"a": {"b":{"c": "foo"}}}'::jsonb , VARIADIC ARRAY['a','b']);
```
