### ISSUE TITLE
trouble with multiple CTE's

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#269]
`WITH a as (SELECT ...), b as (SELECT * FROM a) SELECT * FROM b` generates a panic:

```
$ make sql
sqlc generate
panic: relation "queued_job_id" does not exist

goroutine 1 [running]:
github.com/kyleconroy/sqlc/internal/dinosql.NewQueryCatalog(0xc0001f2e10, 0xc000483c50, 0x1, 0x1)
	/Users/kevin/src/github.com/kyleconroy/sqlc/internal/dinosql/parser.go:628 +0x2e8
github.com/kyleconroy/sqlc/internal/dinosql.sourceTables(0xc0001f2e10, 0x46840a0, 0xc000426690, 0x4, 0x4681b20, 0x33d, 0x4, 0xb)
	/Users/kevin/src/github.com/kyleconroy/sqlc/internal/dinosql/parser.go:692 +0x1fd
github.com/kyleconroy/sqlc/internal/dinosql.outputColumns(0xc0001f2e10, 0x46840a0, 0xc000426690, 0x4, 0xc0005353e0, 0x1, 0x1, 0xc0001d0680)
	/Users/kevin/src/github.com/kyleconroy/sqlc/internal/dinosql/parser.go:729 +0x73
github.com/kyleconroy/sqlc/internal/dinosql.parseQuery(0xc0001f2e10, 0x4683820, 0xc0004a5d00, 0xc0003d7500, 0x967, 0xc0001d0600, 0x8, 0x10)
	/Users/kevin/src/github.com/kyleconroy/sqlc/internal/dinosql/parser.go:445 +0x50a
github.com/kyleconroy/sqlc/internal/dinosql.ParseQueries(0xc0001f2e10, 0xc000232430, 0x9, 0x45778a6, 0xa, 0xc000232440, 0x9, 0xc000232460, 0x10, 0xc000232450, ...)
	/Users/kevin/src/github.com/kyleconroy/sqlc/internal/dinosql/parser.go:240 +0x636
github.com/kyleconroy/sqlc/internal/cmd.glob..func4(0x4a6c8c0, 0x4aa2b40, 0x0, 0x0)
	/Users/kevin/src/github.com/kyleconroy/sqlc/internal/cmd/cmd.go:169 +0x105a
github.com/spf13/cobra.(*Command).execute(0x4a6c8c0, 0x4aa2b40, 0x0, 0x0, 0x4a6c8c0, 0x4aa2b40)
	/Users/kevin/src/github.com/spf13/cobra/command.go:833 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001dca00, 0xc0000b5f10, 0x1, 0x1)
	/Users/kevin/src/github.com/spf13/cobra/command.go:917 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/kevin/src/github.com/spf13/cobra/command.go:867
github.com/kyleconroy/sqlc/internal/cmd.Do(0xc00000e090, 0x1, 0x1, 0x467c960, 0xc000010010, 0x467c980, 0xc000010018, 0x467c980, 0xc000010020, 0xc00008e058)
	/Users/kevin/src/github.com/kyleconroy/sqlc/internal/cmd/cmd.go:35 +0x240
main.main()
	/Users/kevin/src/github.com/kyleconroy/sqlc/cmd/sqlc/main.go:10 +0xad
make: *** [Makefile:84: sql] Error 2
```

**Comment by skariel** [comment]
I hit something similar in #321

**Comment by skariel** [comment]
this simpler form also fails:

```sql
WITH run_row AS (
    UPDATE td3.pending_runs_per_user SET total = total - 1
    WHERE user_id = (
        SELECT user_id
        FROM td3.pending_runs_per_user
        WHERE total > 0
        ORDER BY random()
        LIMIT 1
        FOR UPDATE
        SKIP LOCKED
    )
    RETURNING *
)
UPDATE td3.runs SET status = 'wip', ts_start = NOW()
WHERE td3.runs.id = (
    SELECT td3.runs.id
    FROM td3.runs, run_row
    WHERE created_by = run_row.user_id AND status = 'pending'
    ORDER BY td3.runs.ts_updated ASC
    LIMIT 1
    FOR UPDATE
    SKIP LOCKED
)
RETURNING *;

```
