### ISSUE TITLE
mysql parser can't handle parens in where clause

### ISSUE THREAD

**Issue by inconshreveable** [kyleconroy/sqlc#533]
```
/* name: Test :one */
SELECT * FROM foo
WHERE (id = 0 OR id is NULL);
```

Expected: no error

Got:
```
sqlc generate
panic: Failed to handle *sqlparser.ParenExpr in where

goroutine 1 [running]:
github.com/kyleconroy/sqlc/internal/mysql.PackageGenerator.paramsInWhereExpr(0xc0000bf920, 0x11cd011, 0x1, 0xc000190f00, 0xe, 0x10, 0xc00025fd80, 0x0, 0xc000185b86, 0x5, ...)
	/home/runner/work/sqlc/sqlc/internal/mysql/param.go:114 +0xd39
github.com/kyleconroy/sqlc/internal/mysql.PackageGenerator.parseSelect(0xc0000bf920, 0x11cd011, 0x1, 0xc000190f00, 0xe, 0x10, 0xc00025fd80, 0x0, 0xc000185b86, 0x5, ...)
	/home/runner/work/sqlc/sqlc/internal/mysql/parse.go:187 +0x4d2
github.com/kyleconroy/sqlc/internal/mysql.PackageGenerator.parseQueryString(0xc0000bf920, 0x11cd011, 0x1, 0xc000190f00, 0xe, 0x10, 0xc00025fd80, 0x0, 0xc000185b86, 0x5, ...)
	/home/runner/work/sqlc/sqlc/internal/mysql/parse.go:102 +0x10c
github.com/kyleconroy/sqlc/internal/mysql.parsePath(0xc0004197b0, 0x1, 0x1, 0xc0000bf920, 0x11cd011, 0x1, 0xc000190f00, 0xe, 0x10, 0xc00025fd80, ...)
	/home/runner/work/sqlc/sqlc/internal/mysql/parse.go:73 +0x7d7
github.com/kyleconroy/sqlc/internal/mysql.GeneratePkg(0xc00024e7d9, 0x5, 0xc0004197a0, 0x1, 0x1, 0xc0004197b0, 0x1, 0x1, 0x11cd011, 0x1, ...)
	/home/runner/work/sqlc/sqlc/internal/mysql/parse.go:478 +0x1a0
github.com/kyleconroy/sqlc/internal/cmd.parse(0xc00024e7d9, 0x5, 0xc000038084, 0x15, 0xc000185b86, 0x5, 0xc0004197a0, 0x1, 0x1, 0xc0004197b0, ...)
	/home/runner/work/sqlc/sqlc/internal/cmd/generate.go:179 +0x105
github.com/kyleconroy/sqlc/internal/cmd.Generate(0xc000038084, 0x15, 0xba28a0, 0xc0000be010, 0xc0000be010, 0x573cb0, 0x98b3a0)
	/home/runner/work/sqlc/sqlc/internal/cmd/generate.go:137 +0x8f2
github.com/kyleconroy/sqlc/internal/cmd.glob..func3(0x11c1aa0, 0x122ee30, 0x0, 0x0)
	/home/runner/work/sqlc/sqlc/internal/cmd/cmd.go:82 +0xb1
github.com/spf13/cobra.(*Command).execute(0x11c1aa0, 0x122ee30, 0x0, 0x0, 0x11c1aa0, 0x122ee30)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000199180, 0xc0000f5ee8, 0x1, 0x1)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/kyleconroy/sqlc/internal/cmd.Do(0xc0000c2010, 0x1, 0x1, 0xba2880, 0xc0000be000, 0xba28a0, 0xc0000be008, 0xba28a0, 0xc0000be010, 0xc0000a4058)
	/home/runner/work/sqlc/sqlc/internal/cmd/cmd.go:30 +0x20e
main.main()
	/home/runner/work/sqlc/sqlc/cmd/sqlc/main.go:10 +0xad
```

**Comment by JessBellon** [comment]
I forgot to make an issue for it, but this _should_ be fixed in my PR #531.
