### ISSUE TITLE
Support output parameters

### ISSUE THREAD

**Issue by maxhawkins** [kyleconroy/sqlc#540]
Adding a function with an output parameter causes a panic.

SQL:

```sql
CREATE FUNCTION add_em (IN x int, IN y int, OUT sum int)
AS 'SELECT x + y'
LANGUAGE SQL;
```

Output:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4494714]

goroutine 1 [running]:
github.com/kyleconroy/sqlc/internal/postgresql.parseRelation(0x4edfb60, 0x0, 0xc000518b10, 0x0, 0x0)
        /Users/max/sqlc/internal/postgresql/parse.go:141 +0x894
github.com/kyleconroy/sqlc/internal/postgresql.parseTypeName(0x4edfb60, 0x0, 0xc000518b40, 0x0, 0x0)
        /Users/max/sqlc/internal/postgresql/parse.go:63 +0x39
github.com/kyleconroy/sqlc/internal/postgresql.translate(0x4ee38e0, 0xc000704150, 0x4ed53c0, 0xc000539e40, 0x0, 0x0)
        /Users/max/sqlc/internal/postgresql/parse.go:439 +0x2640
github.com/kyleconroy/sqlc/internal/postgresql.(*Parser).Parse(0x5b2f700, 0x4ed6000, 0xc000481c60, 0x279, 0xc00029a280, 0x27a, 0x0, 0x0)
        /Users/max/sqlc/internal/postgresql/parse.go:202 +0x162
github.com/kyleconroy/sqlc/internal/compiler.parseCatalog(0x4edcce0, 0x5b2f700, 0xc00049be60, 0xc00048bd00, 0x1, 0x1, 0x1, 0xc00045a730)
        /Users/max/sqlc/internal/compiler/compile.go:67 +0x27c
github.com/kyleconroy/sqlc/internal/compiler.(*Engine).ParseCatalog(0xc0002bb520, 0xc00048bd00, 0x1, 0x1, 0x1, 0xc00048bd10)
        /Users/max/sqlc/internal/compiler/engine.go:44 +0x68
github.com/kyleconroy/sqlc/internal/cmd.parse(0xc00036f701, 0xc00046b694, 0x9, 0xc000042044, 0x3b, 0x4c62ff7, 0xa, 0xc00048bd00, 0x1, 0x1, ...)
        /Users/max/sqlc/internal/cmd/generate.go:236 +0x127
github.com/kyleconroy/sqlc/internal/cmd.Generate(0x4c72f01, 0xc000042044, 0x3b, 0x4ed5ee0, 0xc00018a010, 0x41d1970, 0x4b0f420, 0x0)
        /Users/max/sqlc/internal/cmd/generate.go:140 +0x8fb
github.com/kyleconroy/sqlc/internal/cmd.glob..func3(0x5ac5800, 0x5b2f700, 0x0, 0x0)
        /Users/max/sqlc/internal/cmd/cmd.go:92 +0xfe
github.com/spf13/cobra.(*Command).execute(0x5ac5800, 0x5b2f700, 0x0, 0x0, 0x5ac5800, 0x5b2f700)
        /Users/max/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc00037ec80, 0xc00036ff10, 0x1, 0x1)
        /Users/max/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/max/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/kyleconroy/sqlc/internal/cmd.Do(0xc00019a010, 0x1, 0x1, 0x4ed5ec0, 0xc00018a000, 0x4ed5ee0, 0xc00018a008, 0x4ed5ee0, 0xc00018a010, 0xc00009c058)
        /Users/max/sqlc/internal/cmd/cmd.go:30 +0x201
main.main()
        /Users/max/sqlc/cmd/sqlc/main.go:10 +0xad
```

**Comment by kyleconroy** [comment]
This has [been fixed](https://play.sqlc.dev/p/9ca7e6d4ac8a9e78b4afaf27922663a331c79529510bab3270d74be34da2c60d).
