### ISSUE TITLE
Issue with functions in WHERE clause

### ISSUE THREAD

**Issue by djatwood** [kyleconroy/sqlc#630]
The code below generates without any parameters making it impossible to supply the `WHERE` clause with parameters.

```mysql
/* name: GetConversions :many */
SELECT *
FROM `conversions`
WHERE isnull(`archived_at`) = ?
ORDER BY created_at DESC
LIMIT 25;
```

## Generated Code
```go
const listConversions = `-- name: ListConversions :many
select id, registration_id, code, value, notes, created_by, created_at, confirmed_by, confirmed_at, archived_by, archived_at from conversions where isnull(archived_at) = :v1 order by created_at desc limit 25
`

func (q *Queries) ListConversions(ctx context.Context) ([]Conversion, error) {
	rows, err := q.query(ctx, q.listConversionsStmt, listConversions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversion{}
	for rows.Next() {
		var i Conversion
		if err := rows.Scan(
			&i.ID,
			&i.RegistrationID,
			&i.Code,
			&i.Value,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ConfirmedBy,
			&i.ConfirmedAt,
			&i.ArchivedBy,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
```

**Comment by DanielAtwood** [comment]
Here's the error I get when I try to compile.
```
panic: unknown mysql function type "isnull"

goroutine 1 [running]:
github.com/kyleconroy/sqlc/internal/mysql.functionReturnType(0xc0005316a8, 0x6, 0xc0005316a8, 0x6)
	/Users/media/go/src/github.com/DanielAtwood/sqlc/internal/mysql/functions.go:18 +0x3f4
github.com/kyleconroy/sqlc/internal/mysql.PackageGenerator.parseSelectAliasExpr(0xc0003799b8, 0x5609051, 0x1, 0xc000428780, 0x1, 0x1, 0xc000502020, 0x0, 0xc0003ebe66, 0x5, ...)
	/Users/media/go/src/github.com/DanielAtwood/sqlc/internal/mysql/parse.go:440 +0x663
github.com/kyleconroy/sqlc/internal/mysql.PackageGenerator.parseSelect(0xc0003799b8, 0x5609051, 0x1, 0xc000428780, 0x1, 0x1, 0xc000502020, 0x0, 0xc0003ebe66, 0x5, ...)
	/Users/media/go/src/github.com/DanielAtwood/sqlc/internal/mysql/parse.go:180 +0x407
github.com/kyleconroy/sqlc/internal/mysql.PackageGenerator.parseQueryString(0xc0003799b8, 0x5609051, 0x1, 0xc000428780, 0x1, 0x1, 0xc000502020, 0x0, 0xc0003ebe66, 0x5, ...)
	/Users/media/go/src/github.com/DanielAtwood/sqlc/internal/mysql/parse.go:102 +0x15f
github.com/kyleconroy/sqlc/internal/mysql.parsePath(0xc000472e90, 0x1, 0x1, 0xc0003799b8, 0x5609051, 0x1, 0xc000428780, 0x1, 0x1, 0xc000502020, ...)
	/Users/media/go/src/github.com/DanielAtwood/sqlc/internal/mysql/parse.go:73 +0x7ce
github.com/kyleconroy/sqlc/internal/mysql.GeneratePkg(0xc0003ebe14, 0x2, 0xc000472e80, 0x1, 0x1, 0xc000472e90, 0x1, 0x1, 0x5609051, 0x1, ...)
	/Users/media/go/src/github.com/DanielAtwood/sqlc/internal/mysql/parse.go:477 +0x1a0
github.com/kyleconroy/sqlc/internal/cmd.parseMySQL(0xc0003ebe14, 0x2, 0xc000044004, 0x26, 0xc0003ebe66, 0x5, 0xc000472e80, 0x1, 0x1, 0xc000472e90, ...)
	/Users/media/go/src/github.com/DanielAtwood/sqlc/internal/cmd/generate.go:195 +0xcb
github.com/kyleconroy/sqlc/internal/cmd.Generate(0xc000044004, 0x26, 0x4dbebe0, 0xc0000aa010, 0xc0000aa010, 0x41d4e80, 0x4aa9180)
	/Users/media/go/src/github.com/DanielAtwood/sqlc/internal/cmd/generate.go:152 +0x12d0
github.com/kyleconroy/sqlc/internal/cmd.glob..func3(0x59748c0, 0x59ddec8, 0x0, 0x0)
	/Users/media/go/src/github.com/DanielAtwood/sqlc/internal/cmd/cmd.go:89 +0xb1
github.com/spf13/cobra.(*Command).execute(0x59748c0, 0x59ddec8, 0x0, 0x0, 0x59748c0, 0x59ddec8)
	/Users/media/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004462c0, 0xc000271f10, 0x1, 0x1)
	/Users/media/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/media/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/kyleconroy/sqlc/internal/cmd.Do(0xc0000b6010, 0x1, 0x1, 0x4dbebc0, 0xc0000aa000, 0x4dbebe0, 0xc0000aa008, 0x4dbebe0, 0xc0000aa010, 0xc000098058)
	/Users/media/go/src/github.com/DanielAtwood/sqlc/internal/cmd/cmd.go:30 +0x201
main.main()
	/Users/media/go/src/github.com/DanielAtwood/sqlc/cmd/sqlc/main.go:10 +0xad
```

**Comment by kyleconroy** [comment]
The mysql package is deprecated (#633)

However, the replacement package, engine/dolphin, fails to generate the correct code. Here's what it currently spits out:

```sql
CREATE TABLE conversions (
  body text,
  archived_at datetime NOT NULL DEFAULT NOW(),
  created_at  datetime NOT NULL DEFAULT NOW()
);

/* name: GetConversions :many */
SELECT *
FROM conversions
WHERE isnull(archived_at) = ?
ORDER BY created_at DESC
LIMIT 25;
```

```json
{
  "version": "1",
  "packages": [
    {
      "engine": "_dolphin",
      "path": "go",
      "name": "querytest",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

```go
// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package querytest

import (
	"context"
	"time"
)

const getConversions = `-- name: GetConversions :many
SELECT body, archived_at, created_at
FROM conversions
WHERE isnull(archived_at) = ?
ORDER BY created_at DESC
LIMIT 25
`

func (q *Queries) GetConversions(ctx context.Context, archivedAt time.Time) ([]Conversion, error) {
	rows, err := q.db.QueryContext(ctx, getConversions, archivedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversion
	for rows.Next() {
		var i Conversion
		if err := rows.Scan(&i.Body, &i.ArchivedAt, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
```

**Comment by kyleconroy** [comment]
Here's a reproduction of the issue on the [playground](https://play.sqlc.dev/p/642b852302040e597b750a7a7ac5c11907c3559048109e07e580a33e5b11e689).

**Comment by kyleconroy** [comment]
Closed in favor of https://github.com/kyleconroy/sqlc/issues/657
